### ISSUE TITLE
Code Contribution In javaScript and Python

### ISSUE THREAD

**Issue by codePerfectPlus** [xeoneux/30-Days-of-Code#183]
- I want to contribute to code with JavaScript.
- Unable to clone this repo, getting some issues

error: invalid path '0 - Hello, World./Solution.c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
@xeoneux

**Comment by xeoneux** [comment]
Hi @codePerfectPlus 
Thanks for your interest in 30 Days of Code
Since JS now supports classes, it is very much possible to contribute using JS 😄 
The checkout is failing because you're probably using Windows and there's period in the `Hello, World.` folder. I will rename it so that it's possible for you to clone and contribute 👍

**Comment by xeoneux** [comment]
Done! Please trying checking out now 🤘
