### ISSUE TITLE
why we should have extra "scan.nextLine()" here

### ISSUE THREAD

**Issue by deadstar1** [xeoneux/30-Days-of-Code#24]
https://github.com/xeoneux/30-Days-of-Code/blob/a58d8fc227cdbe2633336882f517bfb0d9e81963/1%20-%20Data%20Types/Solution.java#L20

**Comment by xeoneux** [comment]
Hey, @deadstar1 that's because when the user enters an integer and then hits enter, two things have just been entered - the integer and a "newline" which is `\n`. The method you called, "nextInt" or "nextDouble", only reads in the integer or the decimal, respectively, which leaves the newline in the input stream. But calling nextLine() does read in newlines, which is why we had to call `scan.nextLine()` before the next line could be read. You could have also called `scan.next(),` which would also have read in the new line. Hope that helps 😄
